# from django.urls import path

# from . import views

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('quiz1/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz1, name='quiz1'),
#     path('quiz2/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz2, name='quiz2'),
#     path('quiz3/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz3, name='quiz3'),
#     path('quiz4/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz4, name='quiz4'),
#     path('quiz5/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz5, name='quiz5'),
#     path('quiz6/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz6, name='quiz6'),
#     path('quiz7/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz7, name='quiz7'),
#     path('quiz8/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz8, name='quiz8'),
#     path('quiz9/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiz9, name='quiz9'),
#     path('audio/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.audio, name='audio'),
#     path('cards/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.cards, name='cards'),
#     path('quizphoto/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quizphoto, name='quizphoto'),
#     path('translate/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.translate, name='translate'),
#     path('audio_tts/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.audio_tts, name='audio_tts'),
#     path('video/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.video, name='video'),
#     path('quizOrder/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quizOrder, name='quizOrder'),
#     path('stt/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.stt, name='stt'),
#     path('quiztable/"<str:s>"/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.quiztable, name='quiztable'),
#     path('start/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.start_view, name='start_view'),
#     path('nextslide/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.nextslide_view, name='nextslide_view'),
#     path('end/<str:ifNextBtn>/<int:galery_number>/<int:global_i>/<int:global_i_i>',
#          views.end_view, name='end_view'),
# ]

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('quiz1',
         views.quiz1, name='quiz1'),
    path('quiz2',
         views.quiz2, name='quiz2'),
    path('quiz3',
         views.quiz3, name='quiz3'),
    path('quiz4',
         views.quiz4, name='quiz4'),
    path('quiz5',
         views.quiz5, name='quiz5'),
    path('quiz6',
         views.quiz6, name='quiz6'),
    path('quiz7',
         views.quiz7, name='quiz7'),
    path('quiz8',
         views.quiz8, name='quiz8'),
    path('quiz9',
         views.quiz9, name='quiz9'),
    path('audio',
         views.audio, name='audio'),
    path('cards',
         views.cards, name='cards'),
    path('quizphoto',
         views.quizphoto, name='quizphoto'),
    path('translate',
         views.translate, name='translate'),
    path('audio_tts',
         views.audio_tts, name='audio_tts'),
    path('video',
         views.video, name='video'),
    path('quizOrder',
         views.quizOrder, name='quizOrder'),
    path('stt',
         views.stt, name='stt'),
    path('quiztable',
         views.quiztable, name='quiztable'),
    path('audioQuiz5',
         views.audioQuiz5, name='audioQuiz5'),
    path('start',
         views.start_view, name='start_view'),
    path('nextslide',
         views.nextslide_view, name='nextslide_view'),
    path('end',
         views.end_view, name='end_view'),
]
